# Generated by Django 5.1.7 on 2026-05-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_remove_invoice_discount_remove_invoice_tax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('SALARY', 'Salaries'), ('UTILITY', 'Utilities (Electricity/Water/Internet)'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='eta_item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
